defaults:
  - metric_fn: multi_sinusoid
  - dataset: multi_sinusoid
  - optimizer: adam
  - loss: mse_loss
  - amplitude_estimator: mse
  - evaluation: multi
  - param_sampler: multi
  - _self_

param_sampler:
  n_sinusoids: 8

dataset:
  n_components: 8

batch_size: 2048
device: cuda
n_steps: 250000
log_interval: 1000
output_file: results/multi.mse.8.surrogate.csv

seeds: [2345]
