defaults:
  - _self_
  - metric_fn: multi_sinusoid
  - dataset: multi_sinusoid
  - optimizer: adam
  - loss: fft_loss
  - amplitude_estimator: fft
  - evaluation: multi
  - param_sampler: multi

param_sampler:
  n_sinusoids: 2

dataset:
  n_components: 2

batch_size: 2048
device: cuda
n_steps: 250000
log_interval: 1000
output_file: results/multi.fft.2.surrogate.csv

seeds: [1234]
